services:
  rag-app:
    build: .
    container_name: rag_updater_streamlit
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - OCI_METRICS_DATA=true  # Esto le sirve a tu detector automático si querés forzar producción
    # Si usás variables de entorno para las keys de Gemini/Mistral, las podés mapear acá:
    # env_file:
    #   - .env