services:
  rag-app:
    build: .
    container_name: rag_updater_streamlit
    restart: always
    ports:
     - "8501:8501"
    volumes:
     - .:/app
     - /home/ubuntu/Wallet_forohubdb:/app/oracle_wallet
    env_file:
     - .env
    environment:
     - TNS_ADMIN=/app/Wallet_forohubdb2